sudo: required
services:
  - docker

before_install:
  - docker build -t mettmett/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mettmett/react-test npm run test

after_success:
  - docker build -t mettmett/multi-client ./client
  - docker build -t mettmett/multi-nginx ./nginx
  - docker build -t mettmett/multi-server ./server
  - docker build -t mettmett/multi-worker ./worker
  # login into docker hub 
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
  - docker push mettmett/multi-client
  - docker push mettmett/multi-nginx
  - docker push mettmett/multi-server
  - docker push mettmett/multi-worker
